/**
 * vpatHtmlExport.js
 * Generates a standalone VPAT® 2.5 HTML document from VPAT editor data.
 *
 * Supports two templates:
 *   'wcag22'    – WCAG Edition only (tables 1–4 per principle)
 *   'en301549'  – adds EN 301 549 v3.2.1 chapters 9–12
 *
 * Languages: 'en' | 'sv'
 */

import { wcag22 } from '../data/wcag22.js'
import { eaaRequirements } from '../data/eaa.js'

/* ─── Principles ────────────────────────────────────────────────────────────── */

const PRINCIPLES = ['Perceivable', 'Operable', 'Understandable', 'Robust']

/* ─── Translations ──────────────────────────────────────────────────────────── */

const I18N = {
  en: {
    lang: 'en',
    docTitle:          n => `${n} Accessibility Conformance Report`,
    edition:           'WCAG Edition (Based on VPAT® Version 2.5)',

    /* Product info */
    sectionProductInfo: 'Product Information',
    fieldProduct:       'Name of Product/Version',
    fieldDate:          'Report Date',
    fieldContact:       'Contact Information',
    fieldNotes:         'Notes',
    fieldEvalMethods:   'Evaluation Methods Used',

    /* Applicable Standards */
    sectionStandards:   'Applicable Standards/Guidelines',
    colStandard:        'Standard/Guideline',
    colIncluded:        'Included in Report',
    wcagStdName:        'Web Content Accessibility Guidelines 2.2 (ISO/IEC 40500)',
    wcagStdUrl:         'https://www.w3.org/TR/WCAG22/',
    en301549StdName:    'EN 301 549 v3.2.1 (2021-03)',
    en301549StdUrl:     'https://www.etsi.org/deliver/etsi_en/301500_302000/301549/03.02.01_60/en_301549v030201p.pdf',
    yes:                'Yes',

    /* Terms */
    sectionTerms:       'Terms',
    termsIntro:         'The terms used in the Conformance Level information are defined as follows:',
    terms: {
      'Supports':           'The functionality of the product has at least one method that meets the criterion without known defects or meets with equivalent facilitation.',
      'Partially Supports': 'Some functionality of the product does not meet the criterion.',
      'Does Not Support':   'The majority of product functionality does not meet the criterion.',
      'Not Applicable':     'The criterion is not relevant to the product.',
      'Not Evaluated':      'The product has not been evaluated against the criterion. This can be used only in WCAG 2.x Level AAA.',
    },

    /* WCAG Report */
    sectionWcag:        'WCAG 2.x Report',
    wcagNote:           'Note: When reporting on conformance with the WCAG 2.x Success Criteria, they are organized by principle.',
    tablePrefix:        'Table',
    colCriteria:        'Criteria',
    colConformance:     'Conformance Level',
    colRemarks:         'Remarks and Explanations',

    principles: {
      Perceivable:    'Perceivable',
      Operable:       'Operable',
      Understandable: 'Understandable',
      Robust:         'Robust',
    },
    tableNumbers: { Perceivable: 1, Operable: 2, Understandable: 3, Robust: 4 },

    conformance: {
      'supports':           'Supports',
      'partially-supports': 'Partially Supports',
      'does-not-support':   'Does Not Support',
      'not-applicable':     'Not Applicable',
      'not-evaluated':      'Not Evaluated',
    },

    /* EN 301 549 */
    sectionEN301549:    'EN 301 549 Report',
    en301549Intro:      'The following tables report conformance with EN 301 549 v3.2.1 (2021-03). Clauses in Chapter 9 incorporate WCAG 2.1 Level AA criteria by reference.',
    ch9Title:           'Chapter 9 – Web',
    ch9Note:            'The conformance levels reported below follow the WCAG 2.x criteria incorporated by reference in EN 301 549 Chapter 9. EN 301 549 clause numbers are mapped from the corresponding WCAG Success Criteria.',
    ch10Title:          'Chapter 10 – Non-Web Documents',
    ch10Note:           'Not applicable – this report covers web-based content only. There are no non-web documents within scope of this evaluation.',
    ch11Title:          'Chapter 11 – Non-Web Software',
    ch11Note:           'Not applicable – this report covers web-based content only. There is no non-web software within scope of this evaluation.',
    ch12Title:          'Chapter 12 – Documentation and Support Services',
    ch12Note:           'The following requirements apply to documentation and support services provided with the product.',
    colRequirement:     'Requirement',
    colStatus:          'Status',
    statusFulfilled:    'Fulfilled',
    statusPartial:      'Partially fulfilled',
    statusNotFulfilled: 'Not fulfilled',
    statusNotEvaluated: 'Not evaluated',
    level:              'Level',

    /* Footer */
    footer:             'Based on VPAT® Version 2.5. VPAT® is a registered service mark of ITI.',
    generatedBy:        'Generated by Tillgänglighetsgranskaren',
    printPdf:           'Print / Save as PDF',
  },

  sv: {
    lang: 'sv',
    docTitle:          n => `${n} – Tillgänglighetskonformitetsrapport`,
    edition:           'WCAG-utgåva (baserad på VPAT® Version 2.5)',

    sectionProductInfo: 'Produktinformation',
    fieldProduct:       'Produktnamn/Version',
    fieldDate:          'Rapportdatum',
    fieldContact:       'Kontaktinformation',
    fieldNotes:         'Anmärkningar',
    fieldEvalMethods:   'Använda utvärderingsmetoder',

    sectionStandards:   'Tillämpliga standarder/riktlinjer',
    colStandard:        'Standard/Riktlinje',
    colIncluded:        'Inkluderad i rapport',
    wcagStdName:        'Web Content Accessibility Guidelines 2.2 (ISO/IEC 40500)',
    wcagStdUrl:         'https://www.w3.org/TR/WCAG22/',
    en301549StdName:    'EN 301 549 v3.2.1 (2021-03)',
    en301549StdUrl:     'https://www.etsi.org/deliver/etsi_en/301500_302000/301549/03.02.01_60/en_301549v030201p.pdf',
    yes:                'Ja',

    sectionTerms:       'Termer',
    termsIntro:         'Termerna som används för konformitetsnivåinformation definieras enligt följande:',
    terms: {
      'Stöds':           'Produktens funktionalitet har minst en metod som uppfyller kriteriet utan kända brister, eller uppfyller det med likvärdig lösning.',
      'Stöds delvis':    'En del av produktens funktionalitet uppfyller inte kriteriet.',
      'Stöds ej':        'Majoriteten av produktens funktionalitet uppfyller inte kriteriet.',
      'Ej tillämplig':   'Kriteriet är inte relevant för produkten.',
      'Ej utvärderad':   'Produkten har inte utvärderats mot kriteriet. Kan endast användas för WCAG 2.x nivå AAA.',
    },

    sectionWcag:        'WCAG 2.x-rapport',
    wcagNote:           'Obs: Konformans med WCAG 2.x-kriterierna rapporteras organiserade per princip.',
    tablePrefix:        'Tabell',
    colCriteria:        'Kriterium',
    colConformance:     'Konformitetsnivå',
    colRemarks:         'Anmärkningar och förklaringar',

    principles: {
      Perceivable:    'Uppfattbar',
      Operable:       'Hanterbar',
      Understandable: 'Begriplig',
      Robust:         'Robust',
    },
    tableNumbers: { Perceivable: 1, Operable: 2, Understandable: 3, Robust: 4 },

    conformance: {
      'supports':           'Stöds',
      'partially-supports': 'Stöds delvis',
      'does-not-support':   'Stöds ej',
      'not-applicable':     'Ej tillämplig',
      'not-evaluated':      'Ej utvärderad',
    },

    sectionEN301549:    'EN 301 549-rapport',
    en301549Intro:      'Nedanstående tabeller redovisar konformans med EN 301 549 v3.2.1 (2021-03). Klausulerna i kapitel 9 inkorporerar WCAG 2.1 nivå AA-kriterier.',
    ch9Title:           'Kapitel 9 – Webb',
    ch9Note:            'Konformitetsnivåerna nedan följer WCAG 2.x-kriterierna som inkorporeras i EN 301 549 kapitel 9. EN 301 549-klausulnummer mappas från motsvarande WCAG Success Criteria.',
    ch10Title:          'Kapitel 10 – Icke-webbaserade dokument',
    ch10Note:           'Ej tillämplig – denna rapport täcker webbbaserat innehåll. Inga icke-webbaserade dokument ingår i granskningens scope.',
    ch11Title:          'Kapitel 11 – Icke-webbaserad programvara',
    ch11Note:           'Ej tillämplig – denna rapport täcker webbbaserat innehåll. Ingen icke-webbaserad programvara ingår i granskningens scope.',
    ch12Title:          'Kapitel 12 – Dokumentation och support',
    ch12Note:           'Nedanstående krav gäller dokumentation och supporttjänster som tillhandahålls med produkten.',
    colRequirement:     'Krav',
    colStatus:          'Status',
    statusFulfilled:    'Uppfyllt',
    statusPartial:      'Delvis uppfyllt',
    statusNotFulfilled: 'Ej uppfyllt',
    statusNotEvaluated: 'Ej utvärderat',
    level:              'Nivå',

    footer:             'Baserat på VPAT® Version 2.5. VPAT® är ett registrerat servicemärke tillhörande ITI.',
    generatedBy:        'Genererad av Tillgänglighetsgranskaren',
    printPdf:           'Skriv ut / Spara som PDF',
  },
}

/* ─── Helpers ────────────────────────────────────────────────────────────────── */

function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function nlToBr(str) {
  return esc(str).replace(/\n/g, '<br>')
}

/** Convert English criterion name to WCAG 2.2 URL fragment slug */
function criterionSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

function conformanceBadge(level, t) {
  const label = t.conformance[level] ?? level
  const cls = {
    'supports':           'cl-supports',
    'partially-supports': 'cl-partial',
    'does-not-support':   'cl-no',
    'not-applicable':     'cl-na',
    'not-evaluated':      'cl-ne',
  }[level] ?? 'cl-ne'
  return `<span class="cl ${cls}">${esc(label)}</span>`
}

/* ─── WCAG table section ─────────────────────────────────────────────────────── */

function wcagPrincipleTable(principle, tableNum, vpatCriteria, t, lang) {
  const criteria = wcag22.filter(c => c.principle === principle)
  const princLabel = t.principles[principle]
  const tableId = `table-${principle.toLowerCase()}`

  const rows = criteria.map(c => {
    const entry   = vpatCriteria?.[c.id] ?? {}
    const level   = entry.conformanceLevel ?? 'not-evaluated'
    const remarks = entry.remarks?.trim() || ''
    const slug    = criterionSlug(c.name)
    const wcagUrl = `https://www.w3.org/TR/WCAG22/#${slug}`
    const critName = lang === 'sv' ? c.nameSwedish : c.name

    return `
        <tr>
          <td class="td-criteria">
            <a href="${wcagUrl}" target="_blank" rel="noreferrer">${esc(c.id)}: ${esc(critName)}</a>
            <span class="level-badge level-${c.level.toLowerCase()}" aria-label="${esc(t.level)} ${esc(c.level)}">${esc(c.level)}</span>
          </td>
          <td class="td-level">${conformanceBadge(level, t)}</td>
          <td class="td-remarks">${remarks ? nlToBr(remarks) : '<span class="empty-cell">—</span>'}</td>
        </tr>`
  }).join('')

  return `
    <div class="table-block">
      <h3 id="${tableId}">${esc(t.tablePrefix)} ${tableNum}: ${esc(princLabel)}</h3>
      <table aria-labelledby="${tableId}">
        <caption class="sr-only">${esc(t.tablePrefix)} ${tableNum}: ${esc(princLabel)}</caption>
        <thead>
          <tr>
            <th scope="col" class="th-criteria">${esc(t.colCriteria)}</th>
            <th scope="col" class="th-level">${esc(t.colConformance)}</th>
            <th scope="col" class="th-remarks">${esc(t.colRemarks)}</th>
          </tr>
        </thead>
        <tbody>${rows}
        </tbody>
      </table>
    </div>`
}

/* ─── EN 301 549 Chapter 9 table ─────────────────────────────────────────────── */

function en301549Chapter9(vpatCriteria, t, lang) {
  /* Chapter 9 mirrors WCAG 2.x criteria, clause numbers are "9." + WCAG id */
  const rows = wcag22.map(c => {
    const entry   = vpatCriteria?.[c.id] ?? {}
    const level   = entry.conformanceLevel ?? 'not-evaluated'
    const remarks = entry.remarks?.trim() || ''
    const clause  = `9.${c.id}`
    const critName = lang === 'sv' ? c.nameSwedish : c.name
    const wcagUrl  = `https://www.w3.org/TR/WCAG22/#${criterionSlug(c.name)}`

    return `
        <tr>
          <td class="td-criteria">
            <strong>${esc(clause)}</strong>
            <span class="clause-name"><a href="${wcagUrl}" target="_blank" rel="noreferrer">${esc(critName)}</a></span>
            <span class="level-badge level-${c.level.toLowerCase()}">${esc(c.level)}</span>
          </td>
          <td class="td-level">${conformanceBadge(level, t)}</td>
          <td class="td-remarks">${remarks ? nlToBr(remarks) : '<span class="empty-cell">—</span>'}</td>
        </tr>`
  }).join('')

  return `
    <div class="table-block">
      <h3 id="ch9">${esc(t.ch9Title)}</h3>
      <p class="table-note">${esc(t.ch9Note)}</p>
      <table aria-labelledby="ch9">
        <caption class="sr-only">${esc(t.ch9Title)}</caption>
        <thead>
          <tr>
            <th scope="col" class="th-criteria">${esc(t.colCriteria)}</th>
            <th scope="col" class="th-level">${esc(t.colConformance)}</th>
            <th scope="col" class="th-remarks">${esc(t.colRemarks)}</th>
          </tr>
        </thead>
        <tbody>${rows}
        </tbody>
      </table>
    </div>`
}

/* ─── EN 301 549 Chapter 12 table ────────────────────────────────────────────── */

function en301549Chapter12(eaaStatus, t) {
  const rows = eaaRequirements.map(req => {
    const s         = eaaStatus?.[req.id] ?? { checkedItems: [] }
    const checked   = s.checkedItems.length
    const total     = req.checkItems.length
    const allDone   = total > 0 && checked === total
    const noneDone  = checked === 0
    const pct       = total > 0 ? Math.round((checked / total) * 100) : 0

    let statusLabel, statusCls
    if (allDone)       { statusLabel = t.statusFulfilled;    statusCls = 'cl-supports' }
    else if (noneDone) { statusLabel = t.statusNotEvaluated; statusCls = 'cl-ne' }
    else               { statusLabel = t.statusPartial;      statusCls = 'cl-partial' }

    const note = s.note?.trim() || ''

    return `
        <tr>
          <td class="td-criteria">
            <strong>${esc(req.id)}</strong>
            <span class="clause-name">${esc(req.title)}</span>
            <span class="ch12-pct">${pct}% (${checked}/${total})</span>
          </td>
          <td class="td-level"><span class="cl ${statusCls}">${esc(statusLabel)}</span></td>
          <td class="td-remarks">${note ? nlToBr(note) : '<span class="empty-cell">—</span>'}</td>
        </tr>`
  }).join('')

  return `
    <div class="table-block">
      <h3 id="ch12">${esc(t.ch12Title)}</h3>
      <p class="table-note">${esc(t.ch12Note)}</p>
      <table aria-labelledby="ch12">
        <caption class="sr-only">${esc(t.ch12Title)}</caption>
        <thead>
          <tr>
            <th scope="col" class="th-criteria">${esc(t.colRequirement)}</th>
            <th scope="col" class="th-level">${esc(t.colStatus)}</th>
            <th scope="col" class="th-remarks">${esc(t.colRemarks)}</th>
          </tr>
        </thead>
        <tbody>${rows}
        </tbody>
      </table>
    </div>`
}

/* ─── CSS ────────────────────────────────────────────────────────────────────── */

const CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 1.65;
  color: #1a1a1a;
  background: #fff;
}

.vpat-wrapper {
  max-width: 1060px;
  margin: 0 auto;
  padding: 36px 44px 64px;
}

/* ── Print toolbar ── */
.print-bar {
  display: flex;
  justify-content: flex-end;
  margin-bottom: 20px;
}
.print-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 7px 16px;
  background: #1a73e8;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  font-family: inherit;
}
.print-btn:hover { background: #1558b0; }
@media print { .print-bar { display: none; } }

/* ── Header ── */
.vpat-header {
  border-bottom: 3px solid #1a73e8;
  padding-bottom: 20px;
  margin-bottom: 32px;
}
.vpat-header h1 {
  font-size: 24px;
  font-weight: 700;
  color: #111;
  line-height: 1.3;
  margin-bottom: 6px;
}
.vpat-edition {
  font-size: 13px;
  color: #666;
  font-style: italic;
}

/* ── Sections ── */
.vpat-section {
  margin-bottom: 40px;
}
.vpat-section > h2 {
  font-size: 17px;
  font-weight: 700;
  color: #111;
  padding-bottom: 8px;
  border-bottom: 1.5px solid #e0e0e0;
  margin-bottom: 16px;
}
.section-note,
.table-note {
  font-size: 12px;
  color: #666;
  font-style: italic;
  margin-bottom: 14px;
  padding: 8px 12px;
  background: #f7f9fc;
  border-left: 3px solid #c5d5e8;
  border-radius: 0 4px 4px 0;
}

/* ── Tables ── */
.table-block {
  margin-bottom: 32px;
}
.table-block > h3 {
  font-size: 14px;
  font-weight: 700;
  color: #333;
  margin-bottom: 10px;
  margin-top: 28px;
}
.table-block:first-child > h3 { margin-top: 0; }

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
th {
  background: #f2f4f7;
  color: #444;
  font-weight: 700;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  padding: 9px 12px;
  text-align: left;
  border: 1px solid #d8dce3;
}
td {
  padding: 9px 12px;
  border: 1px solid #d8dce3;
  vertical-align: top;
}
tbody tr:nth-child(even) td { background: #fafbfc; }
tbody tr:hover td { background: #f0f4ff; }

/* ── Column widths ── */
.th-criteria { width: 42%; }
.th-level    { width: 16%; }
.th-remarks  { /* flexible */ }

/* ── Product info table ── */
.info-table th {
  width: 220px;
  font-size: 13px;
  text-transform: none;
  letter-spacing: 0;
  font-weight: 600;
  background: #f7f9fc;
}

/* ── Links ── */
a { color: #1a73e8; text-decoration: none; }
a:hover { text-decoration: underline; }

/* ── Criterion cell ── */
.td-criteria { line-height: 1.5; }
.td-criteria a { font-weight: 500; }
.clause-name { display: block; font-size: 12px; color: #555; margin-top: 2px; }
.ch12-pct { display: inline-block; font-size: 11px; color: #888; margin-top: 3px; }

/* ── Level badges (A / AA / AAA) ── */
.level-badge {
  display: inline-block;
  margin-left: 6px;
  font-size: 10px;
  font-weight: 700;
  padding: 1px 5px;
  border-radius: 3px;
  vertical-align: middle;
  line-height: 1.6;
}
.level-a   { background: #fce8e8; color: #b71c1c; border: 1px solid #f4b8b8; }
.level-aa  { background: #fff8e1; color: #7a5200; border: 1px solid #ffe082; }
.level-aaa { background: #e8f5e9; color: #1b5e20; border: 1px solid #a5d6a7; }

/* ── Conformance level badges ── */
.cl {
  display: inline-block;
  padding: 3px 9px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
  white-space: nowrap;
  line-height: 1.5;
}
.cl-supports  { background: #e8f5e9; color: #1b5e20; border: 1px solid #a5d6a7; }
.cl-partial   { background: #fff8e1; color: #7a5200; border: 1px solid #ffe082; }
.cl-no        { background: #fce4ec; color: #880e4f; border: 1px solid #f48fb1; }
.cl-na        { background: #f3f4f6; color: #555;    border: 1px solid #d1d5db; }
.cl-ne        { background: #fafafa; color: #999;    border: 1px solid #e5e7eb; }

.empty-cell { color: #bbb; }

/* ── Terms ── */
.terms-intro { margin-bottom: 14px; }
.terms-dl {
  display: grid;
  grid-template-columns: 180px 1fr;
  gap: 10px 24px;
  align-items: baseline;
}
.terms-dl dt {
  font-weight: 700;
  color: #222;
  padding-top: 1px;
}
.terms-dl dd { color: #555; }

/* ── Standards table ── */
.standards-table td:last-child { font-weight: 600; color: #1b5e20; }

/* ── Footer ── */
.vpat-footer {
  margin-top: 56px;
  padding-top: 16px;
  border-top: 1px solid #ddd;
  font-size: 11px;
  color: #999;
  line-height: 1.7;
}

/* ── Screen reader only ── */
.sr-only {
  position: absolute;
  width: 1px; height: 1px;
  padding: 0; margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border: 0;
}

/* ── Print ── */
@media print {
  body { font-size: 12px; }
  .vpat-wrapper { max-width: none; padding: 0; }
  .vpat-header { border-bottom-color: #000; }
  .vpat-section { page-break-inside: avoid; }
  .table-block  { page-break-inside: auto; }
  table { page-break-inside: auto; }
  thead { display: table-header-group; }
  tr    { page-break-inside: avoid; }
  a { color: #000; text-decoration: underline; }

  /* Force background colors to print */
  .cl-supports  { background: #e8f5e9 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .cl-partial   { background: #fff8e1 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .cl-no        { background: #fce4ec !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .cl-na        { background: #f3f4f6 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .level-a      { background: #fce8e8 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .level-aa     { background: #fff8e1 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  .level-aaa    { background: #e8f5e9 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
  th            { background: #f2f4f7 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
}

@page { margin: 18mm 22mm; }
`

/* ─── Main export function ───────────────────────────────────────────────────── */

/**
 * Builds a complete standalone VPAT® 2.5 HTML document.
 *
 * @param {object} vpat       – VpatEditor data object
 * @param {object} eaaStatus  – EAA checklist status (from storage.getEaaStatus)
 * @param {'en'|'sv'} lang    – Output language
 * @returns {string}            Complete HTML document as a string
 */
export function buildVpatHtml(vpat, eaaStatus, lang = 'en') {
  const t           = I18N[lang] ?? I18N.en
  const productName = vpat.productName?.trim() || '–'
  const isEU        = vpat.template === 'en301549'
  const title       = t.docTitle(productName)
  const today       = new Date().toLocaleDateString(lang === 'sv' ? 'sv-SE' : 'en-GB', { dateStyle: 'long' })

  const contactHtml = [
    vpat.contactName ? esc(vpat.contactName) : null,
    vpat.contactEmail ? `<a href="mailto:${esc(vpat.contactEmail)}">${esc(vpat.contactEmail)}</a>` : null,
  ].filter(Boolean).join('<br>') || '–'

  /* ── 1. Product information ────────────────────────────────────────────────── */
  const productInfoSection = `
  <section class="vpat-section" aria-labelledby="sec-product">
    <h2 id="sec-product">${esc(t.sectionProductInfo)}</h2>
    <table class="info-table">
      <tbody>
        <tr>
          <th scope="row">${esc(t.fieldProduct)}</th>
          <td>${esc(productName)}${vpat.productVersion ? ' ' + esc(vpat.productVersion) : ''}</td>
        </tr>
        <tr>
          <th scope="row">${esc(t.fieldDate)}</th>
          <td>${esc(vpat.reportDate || '–')}</td>
        </tr>
        <tr>
          <th scope="row">${esc(t.fieldContact)}</th>
          <td>${contactHtml}</td>
        </tr>
        <tr>
          <th scope="row">${esc(t.fieldNotes)}</th>
          <td>${vpat.notes?.trim() ? nlToBr(vpat.notes.trim()) : '–'}</td>
        </tr>
        <tr>
          <th scope="row">${esc(t.fieldEvalMethods)}</th>
          <td>${vpat.evaluationMethods?.trim() ? nlToBr(vpat.evaluationMethods.trim()) : '–'}</td>
        </tr>
      </tbody>
    </table>
  </section>`

  /* ── 2. Applicable Standards ───────────────────────────────────────────────── */
  const en301549Row = isEU ? `
        <tr>
          <td><a href="${t.en301549StdUrl}" target="_blank" rel="noreferrer">${esc(t.en301549StdName)}</a></td>
          <td>${esc(t.yes)}</td>
        </tr>` : ''

  const standardsSection = `
  <section class="vpat-section" aria-labelledby="sec-standards">
    <h2 id="sec-standards">${esc(t.sectionStandards)}</h2>
    <table class="standards-table">
      <thead>
        <tr>
          <th scope="col">${esc(t.colStandard)}</th>
          <th scope="col" style="width:160px">${esc(t.colIncluded)}</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="${t.wcagStdUrl}" target="_blank" rel="noreferrer">${esc(t.wcagStdName)}</a></td>
          <td>${esc(t.yes)}</td>
        </tr>${en301549Row}
      </tbody>
    </table>
  </section>`

  /* ── 3. Terms ──────────────────────────────────────────────────────────────── */
  const termRows = Object.entries(t.terms)
    .map(([term, def]) => `<dt>${esc(term)}</dt><dd>${esc(def)}</dd>`)
    .join('\n        ')

  const termsSection = `
  <section class="vpat-section" aria-labelledby="sec-terms">
    <h2 id="sec-terms">${esc(t.sectionTerms)}</h2>
    <p class="terms-intro">${esc(t.termsIntro)}</p>
    <dl class="terms-dl">
        ${termRows}
    </dl>
  </section>`

  /* ── 4. WCAG 2.x Report ────────────────────────────────────────────────────── */
  const principleTablesHtml = PRINCIPLES
    .map((p, i) => wcagPrincipleTable(p, i + 1, vpat.criteria, t, lang))
    .join('')

  const wcagSection = `
  <section class="vpat-section" aria-labelledby="sec-wcag">
    <h2 id="sec-wcag">${esc(t.sectionWcag)}</h2>
    <p class="section-note">${esc(t.wcagNote)}</p>
    ${principleTablesHtml}
  </section>`

  /* ── 5. EN 301 549 sections (EU template only) ─────────────────────────────── */
  const en301549Section = isEU ? `
  <section class="vpat-section" aria-labelledby="sec-en301549">
    <h2 id="sec-en301549">${esc(t.sectionEN301549)}</h2>
    <p class="section-note">${esc(t.en301549Intro)}</p>

    ${en301549Chapter9(vpat.criteria, t, lang)}

    <div class="table-block">
      <h3 id="ch10">${esc(t.ch10Title)}</h3>
      <p class="table-note">${esc(t.ch10Note)}</p>
    </div>

    <div class="table-block">
      <h3 id="ch11">${esc(t.ch11Title)}</h3>
      <p class="table-note">${esc(t.ch11Note)}</p>
    </div>

    ${en301549Chapter12(eaaStatus, t)}
  </section>` : ''

  /* ── Document ──────────────────────────────────────────────────────────────── */
  return `<!DOCTYPE html>
<html lang="${esc(t.lang)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <style>${CSS}</style>
</head>
<body>
  <div class="vpat-wrapper">

    <div class="print-bar" aria-hidden="true">
      <button class="print-btn" onclick="window.print()">
        &#128438; ${esc(t.printPdf)}
      </button>
    </div>

    <header class="vpat-header">
      <h1>${esc(title)}</h1>
      <p class="vpat-edition">${esc(t.edition)}</p>
    </header>

    ${productInfoSection}
    ${standardsSection}
    ${termsSection}
    ${wcagSection}
    ${en301549Section}

    <footer class="vpat-footer">
      <p>${esc(t.footer)}</p>
      <p>${esc(t.generatedBy)} &middot; ${esc(today)}</p>
    </footer>

  </div>
</body>
</html>`
}
