/**
 * Report translations.
 * Finding body text (title, description, customerDescription, suggestedFix)
 * is written by the auditor and not translated here.
 */
export const i18n = {
  sv: {
    // Cover
    reportTitle:        'Tillgänglighetsrapport',
    preparedFor:        'Upprättad för',
    auditor:            'Granskare',
    date:               'Datum',
    wcagVersion:        'WCAG-version',
    conformanceTarget:  'Konformitetsmål',
    generatedBy:        'Genererad av Tillgänglighetsgranskaren',

    // Section headings
    sec1:  'Försättsblad',
    sec2:  'Sammanfattning för ledning',
    sec3:  'Fynd',
    sec4:  'Teknisk bilaga',
    sec5:  'EAA-kravstatus',

    // Summary
    eaaStatus:          'EAA-efterlevnadsstatus',
    eaaNo:              'Uppfyller EAA: Nej',
    eaaPartial:         'Uppfyller EAA: Delvis',
    eaaYes:             'Uppfyller EAA: Ja',
    eaaNoDesc:          'kritiska brister måste åtgärdas innan EAA-efterlevnad kan uppnås.',
    eaaPartialDesc:     'Grundkraven uppfylls, men viktiga förbättringar behövs. Se rekommendationerna nedan.',
    eaaYesDesc:         'Inga kritiska eller höga öppna brister identifierades. Fortsätt regelbunden granskning.',
    findingDistrib:     'Fyndfördelning',
    topActions:         'Tre mest brådskande åtgärder',
    riskAssessment:     'Riskbedömning',

    riskTextCritical:   (n) => `Webbplatsen har ${n} kritisk${n === 1 ? '' : 'a'} brist${n === 1 ? '' : 'er'} som direkt påverkar möjligheten att uppfylla EAA. Dessa måste åtgärdas snarast. Underlåtenhet att åtgärda dessa brister kan leda till juridiska konsekvenser när lagen träder i kraft.`,
    riskTextHigh:       (n) => `Webbplatsen har ${n} hög${n === 1 ? '' : 'a'} brist${n === 1 ? '' : 'er'} utan kritiska problem. Åtgärd rekommenderas inom närmaste releascykel för att uppnå fullständig WCAG AA-konformitet.`,
    riskTextOk:         () => 'Inga kritiska eller höga brister identifierades. Webbplatsen bedöms uppfylla grundkraven för WCAG AA-konformitet. Rekommendation: åtgärda återstående medium- och lågnivåbrister som en del av kontinuerlig förbättring.',

    // Findings
    finding:            'Fynd',
    page:               'Sida',
    wcagRef:            'WCAG-referens',
    affectedUsers:      'Berörda användare',
    consequence:        'Konsekvens',
    suggestedFix:       'Föreslagen åtgärd',
    customerDesc:       'Förklaring',
    screenshot:         'Screenshot',
    noFindings:         'Inga fynd i denna kategori.',
    criterionLabel:     'Kriterium',
    level:              'Nivå',

    // Technical table
    techTableTitle:     'Komplett fyndtabell',
    colId:              'ID',
    colWcag:            'WCAG',
    colCriterion:       'Kriterium',
    colLevel:           'Nivå',
    colSeverity:        'Allvarlighet',
    colPage:            'Sida',
    colStatus:          'Status',

    // EAA table
    eaaTableTitle:      'EAA-kravstatus',
    colRequirement:     'Krav',
    colCategory:        'Kategori',
    colCompliance:      'Status',
    colChecked:         'Uppfyllda punkter',
    colNote:            'Anteckning',
    fulfilled:          'Uppfyllt',
    partial:            'Delvis',
    notChecked:         'Ej granskat',

    // Severity labels
    critical:   'Kritisk',
    high:       'Hög',
    medium:     'Medium',
    low:        'Låg',

    // Status labels
    open:         'Öppen',
    inProgress:   'Pågår',
    fixed:        'Åtgärdad',
    wontFix:      'Åtgärdas ej',

    // Affected user groups
    vision:     'Synskadade',
    motor:      'Motoriska svårigheter',
    cognitive:  'Kognitiva svårigheter',
    hearing:    'Hörselskadade',
    older:      'Äldre användare',
    all:        'Alla användare',

    // WCAG principles
    Perceivable:    'Uppfattbar',
    Operable:       'Hanterbar',
    Understandable: 'Begriplig',
    Robust:         'Robust',
  },

  en: {
    reportTitle:        'Accessibility Report',
    preparedFor:        'Prepared for',
    auditor:            'Auditor',
    date:               'Date',
    wcagVersion:        'WCAG Version',
    conformanceTarget:  'Conformance Target',
    generatedBy:        'Generated by Accessibility Auditing Tool',

    sec1:  'Cover',
    sec2:  'Executive Summary',
    sec3:  'Findings',
    sec4:  'Technical Annex',
    sec5:  'EAA Requirements Status',

    eaaStatus:          'EAA Compliance Status',
    eaaNo:              'EAA Compliance: No',
    eaaPartial:         'EAA Compliance: Partial',
    eaaYes:             'EAA Compliance: Yes',
    eaaNoDesc:          'critical issues must be resolved before EAA compliance can be achieved.',
    eaaPartialDesc:     'Basic requirements are met, but important improvements are needed. See recommendations below.',
    eaaYesDesc:         'No critical or high open issues were identified. Continue regular auditing.',
    findingDistrib:     'Finding Distribution',
    topActions:         'Three Most Urgent Actions',
    riskAssessment:     'Risk Assessment',

    riskTextCritical:   (n) => `The website has ${n} critical issue${n === 1 ? '' : 's'} directly affecting EAA compliance. These must be resolved immediately. Failure to address these issues may result in legal consequences when the law comes into effect.`,
    riskTextHigh:       (n) => `The website has ${n} high-severity issue${n === 1 ? '' : 's'} without critical problems. Remediation is recommended within the next release cycle to achieve full WCAG AA conformance.`,
    riskTextOk:         () => 'No critical or high issues were identified. The website is assessed to meet the basic requirements for WCAG AA conformance. Recommendation: address remaining medium and low issues as part of continuous improvement.',

    finding:            'Finding',
    page:               'Page',
    wcagRef:            'WCAG Reference',
    affectedUsers:      'Affected Users',
    consequence:        'Impact',
    suggestedFix:       'Suggested Fix',
    customerDesc:       'Explanation',
    screenshot:         'Screenshot',
    noFindings:         'No findings in this category.',
    criterionLabel:     'Criterion',
    level:              'Level',

    techTableTitle:     'Complete Findings Table',
    colId:              'ID',
    colWcag:            'WCAG',
    colCriterion:       'Criterion',
    colLevel:           'Level',
    colSeverity:        'Severity',
    colPage:            'Page',
    colStatus:          'Status',

    eaaTableTitle:      'EAA Requirements Status',
    colRequirement:     'Requirement',
    colCategory:        'Category',
    colCompliance:      'Status',
    colChecked:         'Fulfilled items',
    colNote:            'Note',
    fulfilled:          'Fulfilled',
    partial:            'Partial',
    notChecked:         'Not reviewed',

    critical:   'Critical',
    high:       'High',
    medium:     'Medium',
    low:        'Low',

    open:         'Open',
    inProgress:   'In Progress',
    fixed:        'Fixed',
    wontFix:      "Won't Fix",

    vision:     'Visually impaired',
    motor:      'Motor difficulties',
    cognitive:  'Cognitive difficulties',
    hearing:    'Hearing impaired',
    older:      'Older users',
    all:        'All users',

    Perceivable:    'Perceivable',
    Operable:       'Operable',
    Understandable: 'Understandable',
    Robust:         'Robust',
  },
}

export default i18n
